In [8]:
import pandas as pd
import geopandas as gpd

/Users/wknq25/opt/anaconda3/envs/geocoder_py38/lib/python3.8/site-packages/geopandas/_compat.py:123: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/var/folders/fg/_n1n9v7x7x1bk7m6gwfkv97m0000gp/T/ipykernel_3307/1259499560.py:2: UserWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas will still use PyGEOS by default for now. To force to use and test Shapely 2.0, you have to set the environment variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before importing geopandas:

import os
os.environ['USE_PYGEOS'] = '0'
import geopandas

In a future release, GeoPandas will switch to using Shapely by default. If you are using PyGEOS directly (calling PyGEOS functions on geometries from GeoPandas), this will then stop working and you are encouraged to migrate from PyGEOS to Shapely 2.0 (https://shapely.readthedocs.io/en/latest/migration_pygeos.html).
  import geopandas as gpd

In [15]:
gb1900_file = "output/1851/EW/gb1900/gb1900_EW_1851.geojson"
gb1900_linked_old_file = "analysis/1851/EW/gb1900/gb1900_link_lkup_merge.tsv"
gb1900_linked_new_file = "analysis_geom_test/1851/EW/gb1900/gb1900_link_lkup_merge.tsv"

In [9]:
gb1900 = gpd.read_file(gb1900_file)

In [12]:
gb1900.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1148815 entries, 0 to 1148814
Data columns (total 6 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   gb1900_EW_1851  1148815 non-null  object
 1   pin_id          1148815 non-null  object
 2   final_text      1148815 non-null  object
 3   conparid_51-91  1148815 non-null  int64
 4   CEN_1851        1148815 non-null  int64
 5   geometry        1148815 non-null  geometry
dtypes: geometry(1), int64(2), object(3)
memory usage: 52.6+ MB

In [16]:
gb1900_linked_old  = pd.read_csv(gb1900_linked_old_file, sep = "\t", nrows = 1000)
# gb1900_linked_old = pd.merge(left = gb1900_linked_old, right = gb1900, on = "gb1900_EW_1851", how = "left")
gb1900_linked_old

,RecID,unique_add_id,gb1900_EW_1851,rapidfuzzy_wratio_s
0,3747963,BASINGSTOKE ROAD_1254_1190002,NaN,NaN
1,3747964,BASINGSTOKE ROAD_1254_1190002,NaN,NaN
2,3747965,WASING PLACE_1254_1200001,5856c6ef2c66dc10b8013bbe_1254_1200001,1.0
3,3747966,WASING PLACE_1254_1200001,5856c6ef2c66dc10b8013bbe_1254_1200001,1.0
4,3747967,WASING PLACE_1254_1200001,5856c6ef2c66dc10b8013bbe_1254_1200001,1.0
...,...,...,...,...
995,3748958,THE CATHOLIC CHAPEL UPPER WOOLHAMPTON_1256_120...,5856cd172c66dc10b801425c_1256_1200001,0.9
996,3748959,THE CATHOLIC CHAPEL UPPER WOOLHAMPTON_1256_120...,5856cd172c66dc10b801425c_1256_1200001,0.9
997,3748960,THE CATHOLIC CHAPEL UPPER WOOLHAMPTON_1256_120...,5856cd172c66dc10b801425c_1256_1200001,0.9
998,3748961,THE CATHOLIC CHAPEL UPPER WOOLHAMPTON_1256_120...,5856cd172c66dc10b801425c_1256_1200001,0.9
999,3748962,THE CATHOLIC CHAPEL UPPER WOOLHAMPTON_1256_120...,5856cd172c66dc10b801425c_1256_1200001,0.9

In [17]:
gb1900_linked_new = pd.read_csv(gb1900_linked_new_file, sep = "\t", nrows = 1000)
gb1900_linked_new

,RecID,unique_add_id,gb1900_EW_1851,rapidfuzzy_wratio_s
0,3747963,BASINGSTOKE ROAD_1254_1190002,NaN,NaN
1,3747964,BASINGSTOKE ROAD_1254_1190002,NaN,NaN
2,3747965,WASING PLACE_1254_1200001,5856c6ef2c66dc10b8013bbe_1254_1200001,1.0
3,3747966,WASING PLACE_1254_1200001,5856c6ef2c66dc10b8013bbe_1254_1200001,1.0
4,3747967,WASING PLACE_1254_1200001,5856c6ef2c66dc10b8013bbe_1254_1200001,1.0
...,...,...,...,...
995,3748958,THE CATHOLIC CHAPEL UPPER WOOLHAMPTON_1256_120...,5856cd172c66dc10b801425c_1256_1200001,0.9
996,3748959,THE CATHOLIC CHAPEL UPPER WOOLHAMPTON_1256_120...,5856cd172c66dc10b801425c_1256_1200001,0.9
997,3748960,THE CATHOLIC CHAPEL UPPER WOOLHAMPTON_1256_120...,5856cd172c66dc10b801425c_1256_1200001,0.9
998,3748961,THE CATHOLIC CHAPEL UPPER WOOLHAMPTON_1256_120...,5856cd172c66dc10b801425c_1256_1200001,0.9
999,3748962,THE CATHOLIC CHAPEL UPPER WOOLHAMPTON_1256_120...,5856cd172c66dc10b801425c_1256_1200001,0.9